spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/people_flow_rh
    username: peopleflow
    password: peopleflow
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: "people_flow_rh"
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: people_flow_rh
    default-schema: people_flow_rh

logging:
  level:
    com.peopleflow: DEBUG
    org.flywaydb: DEBUG